spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flyway_t1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: aillo123
  flyway:
    # 开启
    enabled: true
    # 禁止清理数据库表
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用
    baseline-version: 0
    #（根据个人情况设置）
    locations:
      - classpath:db/migration/